# Generated by Django 5.2.17 on 2026-08-26 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, choices=[('arquero', 'Arquero'), ('lateral', 'Lateral'), ('central', 'Central'), ('extremo', 'Extremo'), ('pivot', 'Pivot')], max_length=20)),
                ('sub_position', models.CharField(blank=True, choices=[('arquero', 'Arquero'), ('lateral', 'Lateral'), ('central', 'Central'), ('extremo', 'Extremo'), ('pivot', 'Pivot')], help_text='Ej: Lateral que a veces juega de Pivot', max_length=20)),
                ('coach', models.ForeignKey(blank=True, limit_choices_to={'role': 'coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'athlete'}, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
