# Generated by Django 5.2.17 on 2026-08-27 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(limit_choices_to={'role': 'coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routines', to=settings.AUTH_USER_MODEL)),
                ('athlete', models.ForeignKey(limit_choices_to={'role': 'athlete'}, on_delete=django.db.models.deletion.CASCADE, related_name='routine_assignments', to=settings.AUTH_USER_MODEL)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='routines.routine')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('sets', models.PositiveIntegerField(blank=True, null=True)),
                ('reps', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_exercises', to='routines.routine')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
