# Generated by Django 5.2.17 on 2026-08-31 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wants_to_be_coach',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('coach', 'Entrenador'), ('athlete', 'Deportista')], default='athlete', max_length=10),
        ),
    ]
