# Generated by Django 5.2.17 on 2026-09-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='catalog_slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
